
#http://localhost:8085/ubicaciones/v2/listar controller 2
##http://localhost:8085/ubicaciones/listas controller 1
##http://localhost:8085/swagger-ui/index.html con swagger para probar el controller 2 (el viejo no tiene swagger)
##http://localhost:8085/ubicaciones/v2/1 con el controller 2 (el viejo no tiene endpoint para obtener por id)
