server:
  port: 8085
  error:
    include-message: always

spring:
  application:
    name: ms-bodega
  datasource:
    url: jdbc:oracle:thin:@mmg8hvewk688yrh4_low?TNS_ADMIN=C:/Users/Usuario/Desktop/prueba3FullStrack/Wallet
    username: SCHEMA_BODEGA
    password: FullStack-Bodega1
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Configuración de documentación con Swagger / OpenApi
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Integración con el Servidor de Descubrimiento Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true
#http://localhost:8085/ubicaciones/v2/listar controller 2
##http://localhost:8085/ubicaciones/listas controller 1
##http://localhost:8085/swagger-ui/index.html con swagger para probar el controller 2 (el viejo no tiene swagger)
##http://localhost:8085/ubicaciones/v2/1 con el controller 2 (el viejo no tiene endpoint para obtener por id)
